### ISSUE TITLE
Whatever I do, I can't even get it to run...

### ISSUE THREAD

**Issue by Thundergoltn** [SkyAlumny/fortnite-launcher-for-og-servers#8]
Don't call me stupid but I can't find the launchers .exe file like in the video showing it lol. I followed all the directions but can't get it to run.

**Comment by Thundergoltn** [comment]
I worded that wrong, I cant even get the launcher to run. I found the .exe (Idk what i was talking about)

**Comment by StripperPaws** [comment]
Have you compiled the launcher?

**Comment by Thundergoltn** [comment]
Im new to this so im not for sure, im using visual studio 2022 and its giving me a error when I launch (or try to) the launcher

**Comment by StripperPaws** [comment]
Could you attach a screenshot?

**Comment by Thundergoltn** [comment]
Ima see if I can get the file how it was before, i deleted it 😅

**Comment by SkyAlumny** [comment]
Launcher works perfectly fine. You just need to set it up right

**Comment by Thundergoltn** [comment]
I'm just stuck on how to run it, after I fix all the programs... how do I run it. Like a exercise file or smth?

**Comment by SkyAlumny** [comment]
The Launcher is pretty complex, if you don't know to run the Launcher you will face more issues in the future because you need the basic skills. I can tell that because the launcher does not give any errors just on startup if you installed .net right. 

Use a premade Launcher, Buy your own one or learn C# and how to navigate throw the Visual Studio interface.-

**Comment by Thundergoltn** [comment]
Thank you, that's all I needed. I wasn't using visual studio. I thought it was a file, thanks again 😁

**Comment by SkyAlumny** [comment]
"virtual studio" "I thought it was a file" is crazy. Good Luck
